// Auto-generated by BuildManager
// Generated on: 2025-04-30T22:30:29.323Z

import Page from '../plugins/[utilities]/fivem-greenscreener/html/Page.tsx';

function App() {
  return <Page />;
}

export default App;
