// Auto-generated by cli: webview:build
import Page_example2 from '../plugins/example2/html/Page.tsx';
import Page_misc_example from '../plugins/[misc]/example/html/Page.tsx';

const App = () => {
  return (
    <div className="h-dvh">
      <Page_example2 />
      <Page_misc_example />
    </div>
  );
};

export default App;
