// Auto-generated by BuildManager
// Generated on: 2025-04-25T18:23:20.033Z

import Page from '../plugins/[character]/[auth]/character-create/html/Page';

function App() {
  return <Page />;
}

export default App;
