import * as fs from 'fs/promises';
import * as fsSync from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { builtinModules } from 'module';
import * as esbuild from 'esbuild';
import { build as viteBuild, type InlineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { pluginPageEntry } from '../util/vite-plugin-page-entry.js';
import { minimatch } from 'minimatch';
import { FileManager } from './FileManager.js';
import { Plugin } from '../types/Plugin.js';
import { File } from '../types/File.js';
import { PluginManifest, ScriptList } from '../types/Manifest.js';
import { Logger, createLogger } from '../Logger.js';
import {
  PluginReloadManager,
  ReloadOptions,
  ReloadResult,
} from './PluginReloadManager.js';

type EntryPlatform = 'client' | 'server' | 'shared';

interface ScriptEntry {
  file: File;
  platform: EntryPlatform;
}

/**
 * Detect the legacy stub `Page.tsx` shape:
 *   export default function Page() { return <div></div>; }
 * Stubs trigger a full Vite cold-start that produces a webview with no
 * meaningful contents — about a third of the cold-build time on a 4-plugin
 * tree. When the page is structurally empty we emit a tiny placeholder
 * `index.html` instead.
 */
function isStubPageTsx(source: string): boolean {
  const collapsed = source.replace(/\s+/g, ' ').trim();
  return /^export\s+default\s+function\s+\w+\s*\(\s*\)\s*\{\s*return\s*<div>\s*<\/div>\s*;?\s*\}\s*;?\s*$/.test(
    collapsed
  );
}

/**
 * Externalize every Node built-in, both bare (`http`) and `node:`-prefixed
 * (`node:http`). Without the prefixed variant, `import 'node:fs'` falls
 * through esbuild's bundle path and ends up either failing at runtime or
 * being stubbed by esbuild's polyfill.
 */
const NODE_BUILTIN_EXTERNALS: string[] = [
  ...builtinModules,
  ...builtinModules.map((m) => `node:${m}`),
];

/**
 * The name of the shared vendor resource. When a plugin with this name is
 * present in the registry the build switches into "shared vendor" mode:
 *   - `_shared` builds first via `buildSharedVendor`, emitting `_shared.js`
 *     (a single IIFE that parks React/ReactDOM/i18n/etc on `window`) plus
 *     a Tailwind-processed `style.css`.
 *   - Every other plugin's webview build externalizes the packages listed
 *     in {@link VENDOR_GLOBALS} with rollup `globals` pointing at the
 *     window keys assigned by `_shared.js`.
 *   - Each consumer plugin's generated `fxmanifest.lua` gets
 *     `dependency '_shared'` so FXServer starts the vendor resource first.
 *   - Each consumer plugin's `index.html` is generated by BuildManager
 *     (replacing Vite's auto-emitted file) with `<link>`/`<script>` tags
 *     pointing at `https://cfx-nui-_shared/...`.
 *
 * If no plugin named `_shared` is registered, the build runs in legacy
 * mode (per-plugin self-contained webviews) — this is the contract that
 * keeps the framework usable when the shared resource is removed or
 * renamed.
 */
const SHARED_RESOURCE_NAME = '_shared';

/**
 * Packages externalized from per-plugin webview bundles when `_shared` is
 * present. Each entry maps the bare specifier the plugin source uses to
 * the global name `_shared/main.ts` parks the namespace under on `window`.
 *
 * Keep in lock-step with `src/plugins/[default]/_shared/html/main.ts` —
 * adding a key here without a matching `window.X = X` assignment in the
 * vendor entry leaves consumer bundles with an unresolved external that
 * crashes at NUI load.
 *
 * Notes:
 * - `react/jsx-runtime` is the import the @vitejs/plugin-react JSX
 *   transform inserts; without it React's JSX runtime gets duplicated
 *   into every plugin bundle (~6 KB each). The dev variant catches mode
 *   mismatches between the vendor build and consumer build.
 * - `react-icons` subpaths (`react-icons/md`, `/fa6`, …) are intentionally
 *   NOT externalized: each subpath is a distinct module with hundreds of
 *   named exports and the icons each plugin uses are typically small.
 *   Per-plugin tree-shaking is the right answer here.
 */
const VENDOR_GLOBALS: Record<string, string> = {
  'react': 'React',
  'react/jsx-runtime': 'ReactJSXRuntime',
  'react/jsx-dev-runtime': 'ReactJSXDevRuntime',
  'react-dom': 'ReactDOM',
  'react-dom/client': 'ReactDOMClient',
  'react-i18next': 'ReactI18Next',
  'i18next': 'I18Next',
};

/**
 * Cached esbuild rebuild context. Keyed by source file + platform +
 * sourcemap mode so a context is only reused when its build options
 * actually match. Each context owns an esbuild incremental session: the
 * first call runs a full build, subsequent calls run only the work
 * required to produce a fresh bundle.
 */
interface CachedEsbuildContext {
  ctx: esbuild.BuildContext;
  optionsKey: string;
}

/**
 * Build manager
 * This class provides functionality to build plugins by copying files to a dist directory
 */
class BuildManager {
  private fileManager: FileManager;
  private distPath: string;
  private initialized: boolean = false;
  private logger: Logger;
  private production: boolean;

  /**
   * Cached esbuild build contexts keyed by source file path. A context
   * holds the parsed entrypoint graph and any plugin state in memory, so
   * `ctx.rebuild()` after a 1-byte source edit reuses the previous parse
   * tree and only re-emits the changed module — typically <100 ms versus
   * ~1 s for a fresh `esbuild.build()` cold start. Disposed via
   * `BuildManager.dispose()` when the watcher shuts down.
   */
  private esbuildContexts: Map<string, CachedEsbuildContext> = new Map();

  /**
   * sha256 of each plugin's last-built dist contents, keyed by plugin name.
   * Compared against the freshly-built dist after each transactional rename
   * so the watcher can skip the reload POST when the bytes are unchanged.
   * The dominant case for `_shared` is a Page.tsx edit elsewhere that
   * triggers a recompile producing identical CSS + identical vendor IIFE —
   * historically that was issuing a full FXServer restart cycle (with
   * cascade-stop of every dependent) for no behavioral change, and was the
   * primary trigger for FXServer SIGSEGVs during `_shared` lifecycle churn.
   */
  private distHashes: Map<string, string> = new Map();

  /**
   * Creates a new BuildManager instance
   * @param fileManager The FileManager instance to use for file operations
   * @param distPath Optional path to the distribution directory
   * @param logger Logger instance; defaults to a console-backed logger if omitted
   * @param options.production If true, esbuild minifies and emits external
   *   sourcemaps for server bundles (client bundles never get sourcemaps);
   *   Vite is invoked with `--mode production`. Defaults to false.
   */
  constructor(
    fileManager: FileManager,
    distPath: string = 'dist',
    logger: Logger = createLogger({ prefix: 'BuildManager' }),
    options: { production?: boolean } = {}
  ) {
    this.fileManager = fileManager;
    this.distPath = path.resolve(distPath);
    this.logger = logger;
    this.production = options.production ?? false;
  }

  /**
   * Tear down cached state. The watcher calls this on `SIGINT` so the
   * esbuild worker pool exits cleanly. Safe to call multiple times.
   */
  async dispose(): Promise<void> {
    const contexts = Array.from(this.esbuildContexts.values());
    this.esbuildContexts.clear();
    await Promise.all(
      contexts.map(async ({ ctx }) => {
        try {
          await ctx.dispose();
        } catch (error) {
          this.logger.warn('Failed to dispose esbuild context', error);
        }
      })
    );
  }

  /**
   * Run an esbuild build for `entryPath`, reusing a cached context when
   * the option set matches. Returns the bundle output as in-memory files
   * (`write: false`) so the caller can stage them into the transactional
   * temp dir without baking the destination path into the context. The
   * context survives across rebuilds in a watch session — that's where
   * the watch-latency win comes from.
   */
  private async runEsbuildBundle(
    entryPath: string,
    options: esbuild.BuildOptions
  ): Promise<esbuild.BuildResult & { outputFiles: esbuild.OutputFile[] }> {
    // Cache key encodes every option that would change the produced
    // bundle (platform, externals, minify, sourcemap mode, target,
    // loader). Two builds that differ in any of these need separate
    // contexts.
    const optionsKey = JSON.stringify({
      platform: options.platform,
      external: options.external,
      minify: options.minify,
      sourcemap: options.sourcemap,
      target: options.target,
      format: options.format,
      loader: options.loader,
      metafile: options.metafile,
    });

    const existing = this.esbuildContexts.get(entryPath);
    if (existing && existing.optionsKey !== optionsKey) {
      // Options changed for this entry (e.g. user toggled --prod between
      // builds). Drop the stale context and build a fresh one.
      try {
        await existing.ctx.dispose();
      } catch (error) {
        this.logger.warn('Failed to dispose stale esbuild context', error);
      }
      this.esbuildContexts.delete(entryPath);
    }

    let cached = this.esbuildContexts.get(entryPath);
    if (!cached) {
      // esbuild needs *some* output target even with `write: false` —
      // `sourcemap: 'external'` errors with "Cannot use an external source
      // map without an output path" otherwise. The synthetic outfile here
      // only names the in-memory output (and its .map sibling); the
      // caller stages the bytes to the real transactional path via
      // `writeBundleOutputs`.
      const syntheticOutfile = entryPath.replace(/\.(ts|tsx|js|jsx)$/, '.js');
      const ctx = await esbuild.context({
        ...options,
        entryPoints: [entryPath],
        outfile: syntheticOutfile,
        write: false,
      });
      cached = { ctx, optionsKey };
      this.esbuildContexts.set(entryPath, cached);
    }

    const result = await cached.ctx.rebuild();
    if (!result.outputFiles) {
      throw new Error(
        `esbuild rebuild produced no output files for ${entryPath}`
      );
    }
    return result as esbuild.BuildResult & {
      outputFiles: esbuild.OutputFile[];
    };
  }

  /**
   * Initializes the build manager
   * Must be called before using other methods
   */
  async initialize(): Promise<void> {
    try {
      // Create the dist directory if it doesn't exist
      if (!fsSync.existsSync(this.distPath)) {
        await fs.mkdir(this.distPath, { recursive: true });
      }

      this.initialized = true;
      this.logger.info('BuildManager initialized successfully');
    } catch (error) {
      this.logger.error('Failed to initialize BuildManager', error);
      throw new Error('Failed to initialize BuildManager', { cause: error });
    }
  }

  private reloadManager: PluginReloadManager | null = null;

  /**
   * Initializes the reload manager
   * @param options Configuration options for the reload manager
   */
  async initializeReloadManager(options: ReloadOptions = {}): Promise<void> {
    // Construct the manager unconditionally and let it own the probe-retry
    // policy. Previous behavior nulled `reloadManager` on first-call failure,
    // which permanently disabled hot reload for the rest of the session even
    // if FXServer started later. The manager itself now retries on every
    // reload attempt via `ensureInitialized` (PR-06).
    this.reloadManager = new PluginReloadManager(options);
    const ok = await this.reloadManager.initialize();
    if (ok) {
      this.logger.info('✓ Reload manager initialized successfully');
    } else {
      this.logger.warn(
        '⚠ Reload manager probe failed; will retry on each reload attempt'
      );
    }
  }

  /**
   * Reloads a plugin after building
   * @param pluginNameOrPath The name or path of the plugin to reload
   * @returns The result of the reload operation
   */
  async reloadPlugin(pluginNameOrPath: string): Promise<ReloadResult> {
    if (!this.reloadManager) {
      return {
        success: false,
        message: 'Reload manager not initialized',
      };
    }

    try {
      // Get the plugin
      const plugin = this.getPluginFromNameOrPath(pluginNameOrPath);

      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      // Reload the plugin
      const result = await this.reloadManager.reloadPlugin(plugin);

      if (result.success) {
        this.logger.info(`✓ Plugin ${plugin.pluginName} reloaded successfully`);
      } else {
        this.logger.warn(
          `⚠ Plugin ${plugin.pluginName} reload failed: ${result.message}`
        );
      }

      return result;
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      this.logger.error(`Error reloading plugin ${pluginNameOrPath}:`, error);

      return {
        success: false,
        message: `Failed to reload plugin ${pluginNameOrPath}: ${errorMessage}`,
      };
    }
  }

  /**
   * Builds a plugin transactionally: stages all output into
   * `<destDir>.tmp.<pid>`, then atomically swaps it into `<destDir>` only
   * after every step succeeds. On any failure the temp dir is removed and the
   * existing `<destDir>` is left untouched, so partially-built outputs never
   * become visible to FXServer.
   *
   * Note (Windows): `fs.rm` of the existing `<destDir>` can fail with
   * EBUSY/EPERM if FXServer holds an open handle. In that case the temp dir
   * remains on disk and can be recovered by `sweepOrphans()` on the next
   * build with `--no-clean` (or by a fresh `--clean` rebuild). Coordinating
   * with FXServer's resource scan is out of scope for this PR.
   *
   * @param pluginNameOrPath The name or path of the plugin to build
   * @param reload Whether to trigger a hot reload after the build
   * @param options.skipVite If true, copy the existing dist `html/` dir
   *   into the temp dir instead of running Vite. Used by the watcher's
   *   file-kind routing so a TS-only edit doesn't pay the Vite cold start.
   */
  async buildPlugin(
    pluginNameOrPath: string,
    reload: boolean = false,
    options: { skipVite?: boolean } = {}
  ): Promise<{ distChanged: boolean }> {
    this.ensureInitialized();

    let tmpDir: string | undefined;

    try {
      const plugin = this.getPluginFromNameOrPath(pluginNameOrPath);
      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      if (plugin.manifestError) {
        throw new Error(
          `Cannot build plugin ${plugin.pluginName}: ${plugin.manifestError}`
        );
      }
      if (!plugin.manifest) {
        throw new Error(
          `Cannot build plugin ${plugin.pluginName}: plugin.json is missing or unreadable`
        );
      }

      this.logger.info(`Building plugin: ${plugin.pluginName}`);

      const destDir = this.getPluginDestDir(plugin);
      tmpDir = `${destDir}.tmp.${process.pid}`;

      if (fsSync.existsSync(tmpDir)) {
        await fs.rm(tmpDir, { recursive: true, force: true });
      }
      await fs.mkdir(path.dirname(destDir), { recursive: true });
      await fs.mkdir(tmpDir, { recursive: true });

      // File-kind routing fast path: when the watcher knows nothing under
      // `html/` changed, copy the previous Vite output into the temp dir
      // and skip the bundler. Falls back to a full Vite build if the
      // previous output isn't on disk (first build, or a prior failure
      // wiped it).
      const existingHtmlDir = path.join(destDir, 'html');
      // Phase 1: webview build (always sequential, before scripts and
      // assets) — `buildPluginPageTsx` returns the set of plugin-local
      // source files Vite bundled, so subsequent asset-copy steps can
      // skip emitting raw copies of files that are already inlined into
      // `main.js` (e.g. translations/*.json).
      let viteImports: Set<string>;
      if (options.skipVite && fsSync.existsSync(existingHtmlDir)) {
        const tmpHtmlDir = path.join(tmpDir, 'html');
        await fs.cp(existingHtmlDir, tmpHtmlDir, { recursive: true });
        this.logger.info(
          `Skipped Vite for ${plugin.pluginName}: copied previous html/ dist forward`
        );
        // Empty set under skipVite — we don't have the cached graph from
        // the previous build. JSONs imported by the cached webview will
        // get re-copied to dist as raw assets; harmless duplication, only
        // visible on the dev fast-path.
        viteImports = new Set<string>();
      } else {
        viteImports = await this.buildPluginPageTsx(plugin, tmpDir);
      }

      // The shared vendor resource owns its `html/` output entirely (built
      // by `buildSharedVendor` above): the source `html/main.ts` is its
      // Vite entry, not a script to bundle, and `html/style.css` is the
      // pre-compile Tailwind input — copying it as an "other file" would
      // overwrite the compiled stylesheet `buildSharedVendor` just wrote.
      const isShared = this.isSharedVendorPlugin(plugin);

      // Phase 2: script bundlers (TS + JS) in parallel. Their metafiles
      // contribute to the import set so phase-3 asset copies can skip
      // sources that were inlined into the IIFE.
      let scriptImports = new Set<string>();
      if (!isShared) {
        const [tsImports, jsImports] = await Promise.all([
          this.buildPluginTs(plugin, tmpDir),
          this.buildPluginJs(plugin, tmpDir),
        ]);
        scriptImports = new Set<string>([...tsImports, ...jsImports]);
      }

      // Phase 3: assets (Lua, JSON, others) and manifest, in parallel.
      // The `excludePaths` union (Vite + esbuild imports) suppresses
      // raw copies of bundled-in sources. Ordering scripts-before-assets
      // adds a few ms of serialization vs the previous "all parallel"
      // path, which is negligible compared to esbuild/Vite cost.
      const importedSources = new Set<string>([
        ...viteImports,
        ...scriptImports,
      ]);
      const buildSteps: Promise<unknown>[] = [
        this.buildPluginLua(plugin, tmpDir),
        this.buildPluginJson(plugin, tmpDir, importedSources),
        this.buildPluginManifest(plugin, tmpDir),
      ];
      if (!isShared) {
        buildSteps.push(
          this.buildPluginOtherFiles(plugin, tmpDir, importedSources)
        );
      }
      await Promise.all(buildSteps);

      // Hash the staged tmp dir BEFORE swapping. If it matches the
      // prior build's hash AND the destination already exists, skip the
      // swap entirely — neither disk content nor FXServer state needs
      // to change. Without this short-circuit the rm+rename runs on
      // every build, briefly disrupting FXServer's open file handles
      // even when the resource is byte-identical.
      const newHash = await this.hashDir(tmpDir);
      const prevHash = this.distHashes.get(plugin.pluginName);
      const destExists = fsSync.existsSync(destDir);
      const distChanged = !destExists || prevHash !== newHash;

      if (!distChanged) {
        await fs.rm(tmpDir, { recursive: true, force: true });
        tmpDir = undefined;
        this.logger.info(
          `✓ Plugin ${
            plugin.pluginName
          } built successfully to ${this.pathToDisplay(destDir)} (dist unchanged)`
        );
        return { distChanged: false };
      }

      // Stop → swap → start. The stop guarantees FXServer has released
      // its script env (and on Windows, its open file handles to the
      // dist tree) before we rm the destDir. This closes both the
      // EBUSY/EPERM rm hazard AND the partial-script-load cascade where
      // the rebuilt resource began starting before the previous one was
      // fully torn down (`Failed to load script player.lua` etc).
      //
      // The lifecycle is gated on `reload && reloadManager.isHealthy()`
      // — a one-off `pnpm build` (no watch) skips it and falls back to
      // the legacy hot-swap path. Same for builds that ran while
      // FXServer is offline.
      const useLifecycle =
        reload &&
        this.reloadManager !== null &&
        this.reloadManager.isHealthy();
      const reloadManager = this.reloadManager;

      if (useLifecycle && reloadManager) {
        const stopResult = await reloadManager.stopResource(plugin.pluginName);
        // 'missing' is expected on first deploy — FXServer hasn't
        // indexed the new resource yet. Proceed with the swap; the
        // start that follows will also report 'missing' and the user
        // can `refresh` once to register it.
        //
        // Any OTHER stop failure (HTTP timeout, state-poll timeout,
        // StopResource threw) means we don't actually know whether
        // FXServer has released the dist tree. Proceeding with the
        // rm+rename here is the dist-swap-while-running race we
        // designed the lifecycle to prevent — under save spam, this
        // recovery path was the cascade trigger that ended in the
        // txAdmin-watchdog-restart cold-boot. So we ABORT: clean up
        // the tmp dir, leave the on-disk dist intact, do NOT update
        // distHashes (so the next save re-attempts the lifecycle), and
        // surface the error to the watcher.
        if (!stopResult.success && stopResult.state !== 'missing') {
          await fs.rm(tmpDir, { recursive: true, force: true });
          tmpDir = undefined;
          this.logger.error(
            `✗ Stop failed for ${plugin.pluginName} — aborting deploy to keep the resource and its on-disk dist consistent. ` +
              `FXServer says: ${stopResult.message}`
          );
          throw new Error(
            `Stop failed for ${plugin.pluginName}: ${stopResult.message}`
          );
        }
      }

      if (fsSync.existsSync(destDir)) {
        await fs.rm(destDir, { recursive: true, force: true });
      }
      await fs.rename(tmpDir, destDir);
      tmpDir = undefined;

      this.logger.info(
        `✓ Plugin ${
          plugin.pluginName
        } built successfully to ${this.pathToDisplay(destDir)}`
      );

      if (useLifecycle && reloadManager) {
        const startResult = await reloadManager.startResource(
          plugin.pluginName
        );
        if (!startResult.success) {
          // Don't update distHashes — leaving the previous (or
          // empty) hash in place means the next rebuild's
          // `distChanged` check will fire and re-attempt the
          // lifecycle. Updating it now would mark a half-deployed
          // resource as "successfully shipped" and the next no-op
          // save would silently skip the retry.
          this.logger.warn(
            `⚠ Start failed for ${plugin.pluginName}: ${startResult.message}`
          );
        } else {
          this.distHashes.set(plugin.pluginName, newHash);
          this.logger.info(
            `✓ Plugin ${plugin.pluginName} reloaded (state: ${startResult.state ?? 'started'})`
          );
        }
      } else {
        // No lifecycle (one-off `pnpm build` or unhealthy reload
        // manager). The dist on disk is now authoritative; record
        // its hash so a subsequent watch session can short-circuit
        // identical rebuilds.
        this.distHashes.set(plugin.pluginName, newHash);
      }

      return { distChanged: true };
    } catch (error) {
      this.logger.error(`Error building plugin ${pluginNameOrPath}`, error);
      if (tmpDir) {
        try {
          await fs.rm(tmpDir, { recursive: true, force: true });
        } catch (cleanupError) {
          this.logger.warn(
            `⚠ Failed to clean up temp build dir ${tmpDir}`,
            cleanupError
          );
        }
      }
      throw new Error(`Failed to build plugin ${pluginNameOrPath}`, {
        cause: error,
      });
    }
  }

  /**
   * Builds Lua files for a plugin
   * @param pluginNameOrPath The name or path of the plugin, or the Plugin object
   * @param outputDir Override the destination directory (used by transactional buildPlugin to stage into a temp dir)
   */
  async buildPluginLua(
    pluginNameOrPath: string | Plugin,
    outputDir?: string
  ): Promise<void> {
    this.ensureInitialized();

    try {
      const plugin =
        typeof pluginNameOrPath === 'string'
          ? this.getPluginFromNameOrPath(pluginNameOrPath)
          : pluginNameOrPath;

      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      // Get all Lua files
      const luaFiles = plugin.files.filter((file) =>
        file.fileName.endsWith('.lua')
      );

      if (luaFiles.length === 0) {
        this.logger.info(`No Lua files found in plugin ${plugin.pluginName}`);
        return;
      }

      await this.copyFilesToDist(plugin, luaFiles, outputDir);
      this.logger.info(
        `✓ Built ${luaFiles.length} Lua file(s) for plugin ${plugin.pluginName}`
      );
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      if (typeof pluginNameOrPath === 'string') {
        this.logger.error(
          `Error building Lua files for plugin ${pluginNameOrPath}:`,
          error
        );
        throw new Error(
          `Failed to build Lua files for plugin ${pluginNameOrPath}: ${errorMessage}`
        );
      } else {
        this.logger.error(
          `Error building Lua files for plugin ${pluginNameOrPath.pluginName}:`,
          error
        );
        throw new Error(
          `Failed to build Lua files for plugin ${pluginNameOrPath.pluginName}: ${errorMessage}`
        );
      }
    }
  }

  /**
   * Builds JSON files for a plugin
   * @param pluginNameOrPath The name or path of the plugin, or the Plugin object
   * @param outputDir Override the destination directory (used by transactional buildPlugin to stage into a temp dir)
   */
  async buildPluginJson(
    pluginNameOrPath: string | Plugin,
    outputDir?: string,
    excludePaths?: ReadonlySet<string>
  ): Promise<void> {
    this.ensureInitialized();

    try {
      const plugin =
        typeof pluginNameOrPath === 'string'
          ? this.getPluginFromNameOrPath(pluginNameOrPath)
          : pluginNameOrPath;

      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      // Skip JSON files that the script bundlers already inlined into a
      // bundle (translations imported by Page.tsx, fixture data imported
      // from server.ts, etc.). copyFilesToDist would otherwise emit the
      // raw source alongside the IIFE — pure dead bytes that bloat the
      // resource and confuse downstream tooling.
      const isExcluded = excludePaths && excludePaths.size > 0
        ? (file: File) => excludePaths.has(path.normalize(file.fullPath))
        : () => false;

      // Get all JSON files
      const jsonFiles = plugin.files.filter(
        (file) =>
          file.fileName.endsWith('.json') &&
          file.fileName !== 'plugin.json' &&
          !isExcluded(file)
      );

      if (jsonFiles.length === 0) {
        this.logger.info(`No JSON files found in plugin ${plugin.pluginName}`);
        return;
      }

      await this.copyFilesToDist(plugin, jsonFiles, outputDir);
      this.logger.info(
        `✓ Built ${jsonFiles.length} JSON file(s) for plugin ${plugin.pluginName}`
      );
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      if (typeof pluginNameOrPath === 'string') {
        this.logger.error(
          `Error building JSON files for plugin ${pluginNameOrPath}:`,
          error
        );
        throw new Error(
          `Failed to build JSON files for plugin ${pluginNameOrPath}: ${errorMessage}`
        );
      } else {
        this.logger.error(
          `Error building JSON files for plugin ${pluginNameOrPath.pluginName}:`,
          error
        );
        throw new Error(
          `Failed to build JSON files for plugin ${pluginNameOrPath.pluginName}: ${errorMessage}`
        );
      }
    }
  }

  /**
   * Builds TypeScript files for a plugin
   * @param pluginNameOrPath The name or path of the plugin, or the Plugin object
   * @param outputDir Override the destination directory (used by transactional buildPlugin to stage into a temp dir)
   */
  async buildPluginTs(
    pluginNameOrPath: string | Plugin,
    outputDir?: string
  ): Promise<Set<string>> {
    this.ensureInitialized();

    try {
      const plugin =
        typeof pluginNameOrPath === 'string'
          ? this.getPluginFromNameOrPath(pluginNameOrPath)
          : pluginNameOrPath;

      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      // Manifest-driven entries: only files explicitly declared in
      // `client_scripts`/`server_scripts`/`shared_scripts` become bundles.
      // The previous tree-walked behavior also emitted shared/, html/,
      // and any stray .ts file as standalone IIFEs (~31 MB of dead disk
      // for character-create alone).
      const tsEntries = this.getScriptEntries(plugin).filter(
        (e) =>
          e.file.fileName.endsWith('.ts') && !e.file.fileName.endsWith('.tsx')
      );

      if (tsEntries.length === 0) {
        this.logger.info(`No TypeScript files found in plugin ${plugin.pluginName}`);
        return new Set<string>();
      }

      const destDir = outputDir ?? this.getPluginDestDir(plugin);

      // Aggregate inputs across every entry's metafile so the caller can
      // skip dist-copying source files that were already inlined into a
      // bundle (e.g. JSON imports — see `buildPluginJson`'s exclude path).
      const rawInputs = new Set<string>();

      // Process each TypeScript entry
      for (const entry of tsEntries) {
        const file = entry.file;
        // Get the relative path within the plugin
        const relativePath = path.relative(plugin.fullPath, file.fullPath);

        // Change the extension from .ts to .js for the output file
        const outputRelativePath = relativePath.replace(/\.ts$/, '.js');
        const outputPath = path.join(destDir, outputRelativePath);

        // Create the destination directory if it doesn't exist
        const outputDir = path.dirname(outputPath);
        await fs.mkdir(outputDir, { recursive: true });

        // Server vs. client now flows from the manifest entry, not from a
        // path-substring sniff. `shared_scripts` runs on whichever side
        // requires it; FiveM treats it as both, so we bundle for browser
        // (matches the previous default for `shared/`).
        const isServerScript = entry.platform === 'server';
        const externalPackages = this.getExternalPackages(isServerScript);

        // Configure loader based on file type
        const loader: Record<string, esbuild.Loader> = {
          '.ts': 'ts',
          '.js': 'js',
        };

        this.logger.info(`Bundling TypeScript file: ${relativePath}`);

        try {
          // Bundle the file via a long-lived esbuild context (PR-13).
          // `write: false` is enforced inside `runEsbuildBundle` so the
          // context isn't tied to a specific transactional temp dir —
          // we write the in-memory output ourselves below.
          const result = await this.runEsbuildBundle(file.fullPath, {
            bundle: true,
            format: 'iife', // Use IIFE format for FiveM compatibility
            target: 'es2017',
            // Production builds minify everything. Dev builds stay readable
            // so the watch-loop console traces are debuggable.
            minify: this.production,
            // Sourcemaps:
            //   - Client bundles: never. They're downloaded by every player
            //     who connects, and `sourcesContent` would leak full TS.
            //   - Server bundles: external `.map` siblings in production
            //     (smaller IIFE shipped to FXServer, .map kept on disk for
            //     debugging) and inline in dev (single-file convenience).
            //   - The `.map` filename doesn't match `client/*.js` /
            //     `server/*.js` manifest globs, so it's never listed in
            //     `client_scripts` and never shipped over the wire.
            sourcemap: isServerScript
              ? this.production
                ? 'external'
                : 'inline'
              : false,
            loader,
            logLevel: 'info',
            external: externalPackages.concat(isServerScript ? ['canvas'] : []), // Add canvas as external for server scripts
            // Use node platform for server scripts, browser platform for client scripts
            platform: isServerScript ? 'node' : 'browser',
            // Cheap (~few KB / bundle) and lets us learn which sources
            // were inlined — the caller uses this to suppress redundant
            // dist copies of files that have already been baked into the
            // IIFE.
            metafile: true,
          });
          if (result.metafile) {
            for (const key of Object.keys(result.metafile.inputs)) {
              rawInputs.add(key);
            }
          }

          // Check for errors
          if (result.errors.length > 0) {
            const formatted = await this.logger.formatEsbuildErrors(
              result.errors
            );
            this.logger.error(
              `Errors bundling ${file.fullPath}:\n${formatted.join('\n')}`
            );
            throw new Error(`Failed to bundle ${file.fullPath}`, {
              cause: result.errors[0],
            });
          }

          // Stage the in-memory output to the transactional temp path.
          // esbuild emits one file per entry plus optional `.map`; pick
          // them apart by suffix so a sourcemap doesn't overwrite the .js.
          await this.writeBundleOutputs(result.outputFiles, outputPath);

          // Verify the file was created
          if (!fsSync.existsSync(outputPath)) {
            throw new Error(
              `Failed to verify file exists after bundling: ${outputPath}`
            );
          }
        } catch (bundleError) {
          this.logger.error(
            `Error bundling TypeScript file ${file.fullPath}`,
            bundleError
          );
          throw bundleError;
        }
      }

      this.logger.info(
        `✓ Built ${tsEntries.length} TypeScript file(s) for plugin ${plugin.pluginName}`
      );
      return this.collectPluginLocalImports(rawInputs, plugin);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      if (typeof pluginNameOrPath === 'string') {
        this.logger.error(
          `Error building TypeScript files for plugin ${pluginNameOrPath}:`,
          error
        );
        throw new Error(
          `Failed to build TypeScript files for plugin ${pluginNameOrPath}: ${errorMessage}`
        );
      } else {
        this.logger.error(
          `Error building TypeScript files for plugin ${pluginNameOrPath.pluginName}:`,
          error
        );
        throw new Error(
          `Failed to build TypeScript files for plugin ${pluginNameOrPath.pluginName}: ${errorMessage}`
        );
      }
    }
  }

  /**
   * Builds JavaScript files for a plugin
   * @param pluginNameOrPath The name or path of the plugin, or the Plugin object
   * @param outputDir Override the destination directory (used by transactional buildPlugin to stage into a temp dir)
   */
  async buildPluginJs(
    pluginNameOrPath: string | Plugin,
    outputDir?: string
  ): Promise<Set<string>> {
    this.ensureInitialized();

    try {
      const plugin =
        typeof pluginNameOrPath === 'string'
          ? this.getPluginFromNameOrPath(pluginNameOrPath)
          : pluginNameOrPath;

      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      // Manifest-driven entries: only declared JS files become bundles.
      const jsEntries = this.getScriptEntries(plugin).filter(
        (e) =>
          e.file.fileName.endsWith('.js') && !e.file.fileName.endsWith('.jsx')
      );

      if (jsEntries.length === 0) {
        this.logger.info(`No JavaScript files found in plugin ${plugin.pluginName}`);
        return new Set<string>();
      }

      const destDir = outputDir ?? this.getPluginDestDir(plugin);

      // Aggregate inputs across every entry's metafile (see buildPluginTs).
      const rawInputs = new Set<string>();

      // Process each JavaScript entry
      for (const entry of jsEntries) {
        const file = entry.file;
        // Get the relative path within the plugin
        const relativePath = path.relative(plugin.fullPath, file.fullPath);
        const outputPath = path.join(destDir, relativePath);

        // Create the destination directory if it doesn't exist
        const outputDir = path.dirname(outputPath);
        await fs.mkdir(outputDir, { recursive: true });

        const isServerScript = entry.platform === 'server';
        const externalPackages = this.getExternalPackages(isServerScript);

        this.logger.info(`Bundling JavaScript file: ${relativePath}`);

        try {
          // Bundle the file via a long-lived esbuild context (PR-13).
          const result = await this.runEsbuildBundle(file.fullPath, {
            bundle: true,
            format: 'iife', // Use IIFE format for FiveM compatibility
            target: 'es2017',
            minify: this.production,
            // See sourcemap rationale in `buildPluginTs`. JS-source plugins
            // share the same client/server distinction.
            sourcemap: isServerScript
              ? this.production
                ? 'external'
                : 'inline'
              : false,
            external: externalPackages,
            // Use node platform for server scripts, browser platform for client scripts
            platform: isServerScript ? 'node' : 'browser',
            // See `buildPluginTs`. Same import-graph capture for JS sources.
            metafile: true,
          });
          if (result.metafile) {
            for (const key of Object.keys(result.metafile.inputs)) {
              rawInputs.add(key);
            }
          }

          // Check for errors
          if (result.errors.length > 0) {
            const formatted = await this.logger.formatEsbuildErrors(
              result.errors
            );
            this.logger.error(
              `Errors bundling ${file.fullPath}:\n${formatted.join('\n')}`
            );
            throw new Error(`Failed to bundle ${file.fullPath}`, {
              cause: result.errors[0],
            });
          }

          await this.writeBundleOutputs(result.outputFiles, outputPath);

          // Verify the file was created
          if (!fsSync.existsSync(outputPath)) {
            throw new Error(
              `Failed to verify file exists after bundling: ${outputPath}`
            );
          }
        } catch (bundleError) {
          this.logger.error(
            `Error bundling JavaScript file ${file.fullPath}`,
            bundleError
          );
          throw bundleError;
        }
      }

      this.logger.info(
        `✓ Built ${jsEntries.length} JavaScript file(s) for plugin ${plugin.pluginName}`
      );
      return this.collectPluginLocalImports(rawInputs, plugin);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      if (typeof pluginNameOrPath === 'string') {
        this.logger.error(
          `Error building JavaScript files for plugin ${pluginNameOrPath}:`,
          error
        );
        throw new Error(
          `Failed to build JavaScript files for plugin ${pluginNameOrPath}: ${errorMessage}`
        );
      } else {
        this.logger.error(
          `Error building JavaScript files for plugin ${pluginNameOrPath.pluginName}:`,
          error
        );
        throw new Error(
          `Failed to build JavaScript files for plugin ${pluginNameOrPath.pluginName}: ${errorMessage}`
        );
      }
    }
  }

  /**
   * Whether a `_shared` plugin is registered with the FileManager. Used to
   * decide whether per-plugin webviews externalize the vendor packages or
   * stay self-contained. Cached implicitly by the FileManager registry —
   * the watcher refreshes it on registry changes.
   */
  private isSharedVendorAvailable(): boolean {
    return this.fileManager.getPluginsByName(SHARED_RESOURCE_NAME).length > 0;
  }

  /**
   * Whether `plugin` is the shared vendor resource itself. Used to dispatch
   * to {@link buildSharedVendor} instead of the page-tsx pipeline.
   */
  isSharedVendorPlugin(plugin: Plugin): boolean {
    return plugin.pluginName === SHARED_RESOURCE_NAME;
  }

  /**
   * Whether `plugin` ships a real (non-stub) Page.tsx and therefore
   * generates an `index.html` that references the shared vendor URLs.
   * Plugins without a Page.tsx — or with the `<div></div>` stub — emit a
   * placeholder HTML that doesn't reference `_shared`, so they don't need
   * the implicit dependency.
   */
  private pluginHasConsumerWebview(plugin: Plugin): boolean {
    const pageTsxFile = plugin.files.find(
      (file) =>
        file.fileName === 'Page.tsx' &&
        (file.fullPath.includes('/html/') ||
          file.fullPath.includes('\\html\\'))
    );
    if (!pageTsxFile) return false;
    let source: string;
    try {
      source = fsSync.readFileSync(pageTsxFile.fullPath, 'utf-8');
    } catch {
      // If the file disappeared between scan and manifest emission, assume
      // it's a real page so we err on the side of declaring the dep.
      return true;
    }
    return !isStubPageTsx(source);
  }

  /**
   * Generate `index.html` for a consumer plugin built in lib/IIFE mode.
   * Vite's lib mode doesn't emit an HTML entry; we write one that pulls the
   * shared vendor JS and Tailwind CSS from `https://cfx-nui-_shared/...`
   * before loading the plugin's own `main.js`. Cross-resource asset
   * loading is whitelisted for every cfx-nui origin in
   * `code/components/nui-resources/src/ResourceUI.cpp` (see
   * memory/project_pr19_shared_vendor.md), so these `<script>`/`<link>`
   * tags resolve as long as the consumer's `fxmanifest.lua` declares
   * `dependency '_shared'`.
   */
  private async writeConsumerIndexHtml(
    plugin: Plugin,
    htmlOutputDir: string
  ): Promise<void> {
    const title = this.escapeHtml(plugin.pluginName);
    const pluginCssPath = path.join(htmlOutputDir, 'style.css');
    const hasPluginCss = fsSync.existsSync(pluginCssPath);
    // Cache-bust the cfx-nui-_shared/* URLs with the first 8 hex chars of
    // the vendor bundle's dist hash. CEF caches by URL, and without a
    // changing query string a stale `_shared.js` (e.g. from a prior
    // session, before VENDOR_GLOBALS or main.ts was edited) will keep
    // being served even after FXServer restarts the resource — which
    // surfaces as `ReferenceError: ReactJSXRuntime is not defined` in
    // every consumer's main.js the first time the hashes diverge. Empty
    // string when `_shared` hasn't been built yet (cold-build edge); the
    // build orders `_shared` first so consumers see a populated hash in
    // every normal flow.
    const sharedHash = this.distHashes.get(SHARED_RESOURCE_NAME) ?? '';
    const sharedQuery = sharedHash ? `?v=${sharedHash.slice(0, 8)}` : '';
    const html = [
      '<!doctype html>',
      '<html>',
      '<head>',
      '  <meta charset="utf-8">',
      `  <title>${title}</title>`,
      // Paths under cfx-nui-_shared/ resolve relative to the _shared
      // resource root, and the manifest's `files{}` block exposes both
      // assets under html/. Without that prefix the browser gets 404s
      // and qb-multicharacter throws ReferenceError on the first vendor
      // global (because window.React etc never got assigned).
      `  <link rel="stylesheet" href="https://cfx-nui-_shared/html/style.css${sharedQuery}">`,
      ...(hasPluginCss
        ? ['  <link rel="stylesheet" href="./style.css">']
        : []),
      '</head>',
      '<body>',
      '  <div id="root"></div>',
      `  <script src="https://cfx-nui-_shared/html/_shared.js${sharedQuery}"></script>`,
      '  <script src="./main.js"></script>',
      '</body>',
      '</html>',
      '',
    ].join('\n');
    await fs.writeFile(path.join(htmlOutputDir, 'index.html'), html, 'utf-8');
  }

  /**
   * Minimal HTML entity escape for the page title. The other interpolated
   * strings are static literals.
   */
  private escapeHtml(s: string): string {
    return s
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  /**
   * Build the shared vendor resource. The entry is `_shared/html/main.ts`,
   * which imports React/ReactDOM/i18n/etc and parks them on `window`, plus
   * `./style.css` (Tailwind + theme) which Vite emits as a sibling. Output
   * is a single `_shared.js` IIFE and `style.css` under the resource's
   * `html/` directory — exactly the names declared in `_shared/plugin.json`'s
   * `files {}` block, so FXServer exposes them at
   * `https://cfx-nui-_shared/_shared.js` and `https://cfx-nui-_shared/style.css`.
   */
  private async buildSharedVendor(
    plugin: Plugin,
    outputDir: string
  ): Promise<void> {
    const mainTsFile = plugin.files.find(
      (f) =>
        f.fileName === 'main.ts' &&
        (f.fullPath.includes('/html/') || f.fullPath.includes('\\html\\'))
    );
    if (!mainTsFile) {
      throw new Error(
        `Shared vendor resource is missing html/main.ts: expected at ${plugin.displayPath}/html/main.ts`
      );
    }

    const htmlOutputDir = path.join(outputDir, 'html');
    await fs.mkdir(htmlOutputDir, { recursive: true });

    const mode = this.production ? 'production' : 'development';
    this.logger.info(
      `Building shared vendor (mode=${mode}) → outDir=${this.pathToDisplay(
        htmlOutputDir
      )}`
    );

    const previousNodeEnv = process.env.NODE_ENV;
    if (this.production) {
      process.env.NODE_ENV = 'production';
    }
    try {
      const config: InlineConfig = {
        // Skip auto-discovery of vite.config.ts — its `virtual:plugin-page`
        // resolver throws when U_CORE_PLUGIN_PAGE is unset, and the shared
        // vendor never loads that virtual module. Bringing in the React
        // plugin is also unnecessary; this entry is plain TS.
        configFile: false,
        mode,
        logLevel: 'warn',
        // Vite's lib mode does NOT auto-replace `process.env.NODE_ENV` the
        // way app mode does. React's source has hundreds of these checks;
        // without the replacement, the bundled output references `process`
        // at runtime and CEF throws ReferenceError at the first React import.
        define: {
          'process.env.NODE_ENV': JSON.stringify(
            this.production ? 'production' : 'development'
          ),
        },
        build: {
          outDir: htmlOutputDir,
          emptyOutDir: true,
          lib: {
            entry: mainTsFile.fullPath,
            formats: ['iife'],
            name: 'UCoreShared',
            fileName: () => '_shared.js',
          },
          cssCodeSplit: false,
          rollupOptions: {
            output: {
              assetFileNames: (assetInfo) => {
                const name = assetInfo.name ?? '';
                if (name.endsWith('.css')) return 'style.css';
                return 'assets/[name][extname]';
              },
            },
          },
        },
      };
      await viteBuild(config);
    } finally {
      if (previousNodeEnv === undefined) {
        delete process.env.NODE_ENV;
      } else {
        process.env.NODE_ENV = previousNodeEnv;
      }
    }

    const jsPath = path.join(htmlOutputDir, '_shared.js');
    const cssPath = path.join(htmlOutputDir, 'style.css');
    if (!fsSync.existsSync(jsPath)) {
      throw new Error(
        `Shared vendor build did not produce ${jsPath}; check Vite logs`
      );
    }
    if (!fsSync.existsSync(cssPath)) {
      throw new Error(
        `Shared vendor build did not produce ${cssPath}; the Tailwind import in _shared/html/main.ts may have been stripped`
      );
    }

    this.logger.info(
      `✓ Built shared vendor to ${this.pathToDisplay(htmlOutputDir)}`
    );
  }

  /**
   * Hard-fail on installed-React-version skew. With pnpm hoisting + a
   * single workspace there should only be one `react` and one `react-dom`
   * directory under `node_modules/.pnpm`. Two copies means at least one
   * plugin (or `_shared` itself) resolves to a different React than the
   * vendor bundle parks on `window.React`, which produces silent runtime
   * errors at NUI load (hooks fail, dispatcher mismatches, etc).
   *
   * Run before any consumer plugin webview is built. Returns the resolved
   * single version string for log output.
   */
  async assertSingleReactVersion(): Promise<string> {
    const pnpmDir = path.resolve('node_modules/.pnpm');
    let entries: string[];
    try {
      entries = await fs.readdir(pnpmDir);
    } catch (error) {
      throw new Error(
        `Cannot read node_modules/.pnpm to verify React version uniqueness: ${
          error instanceof Error ? error.message : String(error)
        }. Did pnpm install run?`
      );
    }
    const reactDirs = entries.filter((e) => /^react@\d/.test(e));
    const reactDomDirs = entries.filter((e) => /^react-dom@\d/.test(e));
    if (reactDirs.length === 0) {
      throw new Error(
        'No `react@*` directory under node_modules/.pnpm — install dependencies before building'
      );
    }
    if (reactDirs.length > 1) {
      throw new Error(
        `Multiple React versions installed: ${reactDirs.join(
          ', '
        )}. The shared vendor bundle parks one copy on window.React; consumer plugins resolving any other version will fail at NUI load. Resolve via pnpm overrides or peer-dep alignment.`
      );
    }
    if (reactDomDirs.length > 1) {
      throw new Error(
        `Multiple ReactDOM versions installed: ${reactDomDirs.join(
          ', '
        )}. Same failure mode as multiple React versions; resolve before building.`
      );
    }
    return reactDirs[0].replace(/^react@/, '');
  }

  /**
   * Builds the per-plugin webview by handing the plugin's Page.tsx to Vite via
   * the `virtual:plugin-page` module (resolved in vite.config.ts from
   * `U_CORE_PLUGIN_PAGE`). No mutation of `src/webview/App.tsx` — that file is
   * gone; cross-plugin builds are now safe to run in parallel.
   */
  async buildPluginPageTsx(
    pluginNameOrPath: string | Plugin,
    outputDir?: string
  ): Promise<Set<string>> {
    this.ensureInitialized();

    try {
      const plugin =
        typeof pluginNameOrPath === 'string'
          ? this.getPluginFromNameOrPath(pluginNameOrPath)
          : pluginNameOrPath;

      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      // The shared vendor resource has no Page.tsx — it's a vendor bundle,
      // not a UI plugin. Route it through buildSharedVendor.
      if (this.isSharedVendorPlugin(plugin)) {
        const pluginDistDir = outputDir ?? this.getPluginDestDir(plugin);
        await this.buildSharedVendor(plugin, pluginDistDir);
        return new Set<string>();
      }

      const pageTsxFile = plugin.files.find(
        (file) =>
          file.fileName === 'Page.tsx' &&
          (file.fullPath.includes('/html/') ||
            file.fullPath.includes('\\html\\'))
      );

      if (!pageTsxFile) {
        this.logger.info(`No Page.tsx file found in plugin ${plugin.pluginName}`);
        return new Set<string>();
      }

      this.logger.info(
        `Building webview for plugin ${plugin.pluginName} from ${pageTsxFile.displayPath}`
      );

      const pluginDistDir = outputDir ?? this.getPluginDestDir(plugin);
      const htmlOutputDir = path.join(pluginDistDir, 'html');
      await fs.mkdir(htmlOutputDir, { recursive: true });

      // Skip the Vite cold-start when the page is a structural stub
      // (`<div></div>`). Two of the four shipped plugins were stubs and
      // each cost ~3s to compile a webview that rendered nothing.
      const pageSource = await fs.readFile(pageTsxFile.fullPath, 'utf-8');
      if (isStubPageTsx(pageSource)) {
        this.logger.info(
          `Stub Page.tsx detected for ${plugin.pluginName}; skipping Vite and emitting placeholder index.html`
        );
        const indexHtmlPath = path.join(htmlOutputDir, 'index.html');
        await fs.writeFile(
          indexHtmlPath,
          '<!doctype html><html><head><meta charset="utf-8"><title>' +
            plugin.pluginName +
            '</title></head><body><div id="root"></div></body></html>\n'
        );
        this.logger.info(
          `✓ Built webview placeholder for plugin ${plugin.pluginName} to ${this.pathToDisplay(htmlOutputDir)}`
        );
        return new Set<string>();
      }

      const consumerMode = this.isSharedVendorAvailable();
      const rawImports = await this.runViteBuild(
        htmlOutputDir,
        pageTsxFile.fullPath,
        consumerMode ? 'consumer' : 'standalone'
      );

      if (consumerMode) {
        // Lib mode never emits an index.html (Vite only generates one in
        // multi-page / app mode). Synthesize one that loads the shared
        // vendor + style first, then this plugin's IIFE.
        await this.writeConsumerIndexHtml(plugin, htmlOutputDir);
      }

      const indexHtmlPath = path.join(htmlOutputDir, 'index.html');
      if (!fsSync.existsSync(indexHtmlPath)) {
        throw new Error(
          `Failed to generate index.html for plugin ${plugin.pluginName}`
        );
      }

      this.logger.info(
        `✓ Built webview for plugin ${plugin.pluginName} to ${this.pathToDisplay(htmlOutputDir)}`
      );
      return this.collectPluginLocalImports(rawImports, plugin);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      const pluginName =
        typeof pluginNameOrPath === 'string'
          ? pluginNameOrPath
          : pluginNameOrPath.pluginName;

      this.logger.error(`Error building webview for plugin ${pluginName}:`, error);
      throw new Error(
        `Failed to build webview for plugin ${pluginName}: ${errorMessage}`
      );
    }
  }

  /**
   * Build the per-plugin Page.tsx via Vite's programmatic JS API. Calling
   * `build()` in-process (instead of spawning the `vite` CLI as a child
   * process) keeps the dep-prebundle cache, plugin module graph, and
   * Rollup state warm
   * across plugins and across rebuilds within a single `pnpm dev`
   * session — the watch-latency win that the subprocess fork-exec model
   * could never deliver. The page path still flows through
   * `U_CORE_PLUGIN_PAGE`; vite.config.ts's `virtual:plugin-page` plugin
   * reads `process.env.U_CORE_PLUGIN_PAGE` at load time, so we set it on
   * the current process rather than passing it via spawn env.
   */
  private async runViteBuild(
    outputDir: string,
    pluginPagePath: string,
    style: 'standalone' | 'consumer' = 'standalone'
  ): Promise<Set<string>> {
    const mode = this.production ? 'production' : 'development';
    this.logger.info(
      `Running Vite build (JS API, mode=${mode}, style=${style}) → outDir=${outputDir}, page=${pluginPagePath}`
    );

    // The page path used to be carried via `process.env.U_CORE_PLUGIN_PAGE`,
    // but `process.env` is process-global — when consumer Vite builds run
    // in parallel they both overwrite it and end up resolving the
    // `virtual:plugin-page` module to whichever was last written, silently
    // shipping one plugin's React bundle inside another's resource dir.
    // The path now travels as a closure argument to `pluginPageEntry()`,
    // race-free and per-build. NODE_ENV stays on `process.env` because
    // Vite + downstream plugins inspect it via the global directly; that
    // value is consistent across all builds in a single `pnpm build` run.
    const previousNodeEnv = process.env.NODE_ENV;
    if (this.production) {
      process.env.NODE_ENV = 'production';
    }
    try {
      // Consumer mode: lib + IIFE + externalized vendor. The plugin's
      // bundle becomes a single `main.js` that expects `window.React` etc.
      // to exist (parked there by `_shared/_shared.js`, which BuildManager's
      // generated index.html loads first). CSS imported by the plugin
      // source still gets emitted as `style.css` alongside the JS — it's
      // intentionally NOT shared, since each plugin may extend the theme.
      //
      // Both modes pass `configFile: false` and re-add the plugins they
      // need explicitly: the `vite.config.ts` at the project root sets
      // `manualChunks` which is incompatible with `inlineDynamicImports`
      // (forced on by IIFE/lib output) and would error in consumer mode.
      const consumerEntry = path.resolve('src/webview/main.tsx');
      // Lib mode disables Vite's auto-replacement of `process.env.NODE_ENV`,
      // so dev-mode bundles still ship React's `if (process.env.NODE_ENV
      // === 'production')` guards verbatim and crash in CEF the moment
      // they execute. Statically replacing the value here matches what
      // the app-mode default would do.
      const define = {
        'process.env.NODE_ENV': JSON.stringify(
          this.production ? 'production' : 'development'
        ),
      };
      // shadcn-style path alias `@/*` → src/webview/*. Mirrors what
      // tsconfig.webview.json declares so consumer bundles can use the
      // standard shadcn import paths at runtime as well as during type
      // check.
      const resolveAlias = {
        '@': path.resolve('src/webview'),
      };
      const config: InlineConfig =
        style === 'consumer'
          ? {
              configFile: false,
              mode,
              logLevel: 'warn',
              plugins: [pluginPageEntry(pluginPagePath), react()],
              define,
              resolve: { alias: resolveAlias },
              build: {
                outDir: outputDir,
                emptyOutDir: true,
                lib: {
                  entry: consumerEntry,
                  formats: ['iife'],
                  name: 'PluginEntry',
                  fileName: () => 'main.js',
                },
                cssCodeSplit: false,
                rollupOptions: {
                  external: Object.keys(VENDOR_GLOBALS),
                  output: {
                    globals: VENDOR_GLOBALS,
                    assetFileNames: (assetInfo) => {
                      const name = assetInfo.name ?? '';
                      if (name.endsWith('.css')) return 'style.css';
                      return 'assets/[name][extname]';
                    },
                  },
                },
              },
            }
          : {
              configFile: false,
              mode,
              logLevel: 'warn',
              plugins: [pluginPageEntry(pluginPagePath), react()],
              root: path.resolve('src'),
              define,
              resolve: { alias: resolveAlias },
              build: {
                outDir: outputDir,
                emptyOutDir: true,
              },
            };
      const result = await viteBuild(config);
      // Walk the rollup output graph so callers can learn which source
      // files Vite bundled into the webview. Used by buildPluginJson /
      // buildPluginOtherFiles to skip copying assets that have already
      // been baked into `main.js` (e.g. translations/*.json imported by
      // Page.tsx for i18next bundles).
      const raw = new Set<string>();
      const outputs = Array.isArray(result) ? result : [result];
      for (const out of outputs) {
        const chunks = (out as { output?: unknown[] } | null)?.output;
        if (!Array.isArray(chunks)) continue;
        for (const chunk of chunks) {
          const modules = (chunk as { modules?: Record<string, unknown> } | null)
            ?.modules;
          if (!modules) continue;
          for (const id of Object.keys(modules)) raw.add(id);
        }
      }
      return raw;
    } finally {
      if (previousNodeEnv === undefined) {
        delete process.env.NODE_ENV;
      } else {
        process.env.NODE_ENV = previousNodeEnv;
      }
    }
  }

  /**
   * Stage `outputFiles` from an in-memory esbuild build to disk. esbuild
   * emits one bundle per entry plus an optional `.map` sibling; route
   * them by suffix so a sourcemap can't overwrite the JS bundle when
   * iterating in arbitrary order.
   */
  private async writeBundleOutputs(
    outputFiles: esbuild.OutputFile[],
    outputPath: string
  ): Promise<void> {
    const outputDir = path.dirname(outputPath);
    await fs.mkdir(outputDir, { recursive: true });
    for (const out of outputFiles) {
      const target = out.path.endsWith('.map')
        ? `${outputPath}.map`
        : outputPath;
      await fs.writeFile(target, out.contents);
    }
  }

  /**
   * Copies files to the dist directory
   * @param plugin The plugin object
   * @param files The files to copy
   * @param outputDir Override the destination directory (used by transactional buildPlugin to stage into a temp dir)
   * @private
   */
  /**
   * Resolve a heterogeneous set of import paths (esbuild metafile keys are
   * cwd-relative; Vite chunk module IDs are usually absolute) into the
   * subset that lives inside the given plugin's directory tree, normalized
   * for case-insensitive comparison on Windows. Files outside the plugin
   * (e.g. shared `src/webview/` modules, node_modules, virtual modules)
   * are dropped — they're never candidates for `buildPluginJson` /
   * `buildPluginOtherFiles` to copy anyway.
   */
  private collectPluginLocalImports(
    rawPaths: Iterable<string>,
    plugin: Plugin
  ): Set<string> {
    const set = new Set<string>();
    const pluginPrefix = path.normalize(plugin.fullPath).toLowerCase();
    for (const raw of rawPaths) {
      // Rollup represents virtual modules with a leading null byte; drop
      // them. Other non-file IDs (e.g. esbuild plugin prefixes like
      // `vite:react`) get filtered out by the plugin-prefix check below
      // since they don't resolve to anything inside the plugin's tree.
      // Note: a regex like `/^[a-z]+:/i` would also match Windows drive
      // letters (`D:\...`) and silently strip every absolute path on
      // Windows — explicitly avoided.
      if (raw.startsWith('\0')) continue;
      const abs = path.isAbsolute(raw) ? raw : path.resolve(process.cwd(), raw);
      const norm = path.normalize(abs);
      if (norm.toLowerCase().startsWith(pluginPrefix)) {
        set.add(norm);
      }
    }
    return set;
  }

  private async copyFilesToDist(
    plugin: Plugin,
    files: File[],
    outputDir?: string
  ): Promise<void> {
    const destDir = outputDir ?? this.getPluginDestDir(plugin);

    // Ensure the destination directory exists
    await fs.mkdir(destDir, { recursive: true });

    // Copy each file, preserving directory structure within the plugin
    for (const file of files) {
      // Get the relative path within the plugin
      const relativePath = path.relative(plugin.fullPath, file.fullPath);
      const destPath = path.join(destDir, relativePath);

      // Create the destination directory if it doesn't exist
      const destFileDir = path.dirname(destPath);
      await fs.mkdir(destFileDir, { recursive: true });

      // Copy the file
      await fs.copyFile(file.fullPath, destPath);
    }
  }

  /**
   * Gets the destination directory for a plugin
   * @param plugin The plugin object
   * @private
   */
  private getPluginDestDir(plugin: Plugin): string {
    // Use the plugin's parent folders to build the destination path
    let destPath = this.distPath;

    // If the plugin has parent folders, include them in the path
    if (plugin.parents.length > 0) {
      // We only need the last parent entry which contains the full parent path
      // For example, if parents are ['[misc2]', '[misc2]/[sub-sub-folder]'],
      // we only need the last one which already has the full path structure
      const parentPath = plugin.parents[plugin.parents.length - 1];

      // Combine the parent path with the plugin name
      destPath = path.join(this.distPath, parentPath, plugin.pluginName);
    } else {
      // No parent folders, just place directly under dist
      destPath = path.join(this.distPath, plugin.pluginName);
    }

    return destPath;
  }

  /**
   * Gets a Plugin object from a name or path
   * @param pluginNameOrPath The name or path of the plugin
   * @private
   */
  private getPluginFromNameOrPath(
    pluginNameOrPath: string
  ): Plugin | undefined {
    if (pluginNameOrPath.includes(path.sep)) {
      // It's a path
      return this.fileManager.getPluginByPath(pluginNameOrPath);
    } else {
      // It's a name
      return this.fileManager.getPlugin(pluginNameOrPath);
    }
  }

  /**
   * Converts a path to display format (with forward slashes)
   * @param filePath The path to convert
   * @private
   */
  private pathToDisplay(filePath: string): string {
    return filePath.replace(/\\/g, '/');
  }

  /**
   * Builds all plugins
   */
  async buildAllPlugins(reload: boolean = false): Promise<void> {
    this.ensureInitialized();

    try {
      const plugins = this.fileManager.getAllPlugins();

      if (plugins.length === 0) {
        this.logger.info('No plugins found to build');
        return;
      }

      this.logger.info(`Building all ${plugins.length} plugins...`);

      const shared = plugins.find((p) => this.isSharedVendorPlugin(p));
      const consumers = plugins.filter((p) => !this.isSharedVendorPlugin(p));

      if (shared) {
        // Hard fail before any consumer build if the workspace has more
        // than one React copy — the externalized consumer bundles all
        // resolve their imports to whichever copy esbuild/Vite picks for
        // the lib build, while window.React comes from _shared. A skew
        // produces silent runtime errors that look like unrelated bugs.
        const reactVersion = await this.assertSingleReactVersion();
        this.logger.info(
          `✓ Single React@${reactVersion} resolved across the workspace`
        );

        // _shared must be on disk before any consumer plugin builds —
        // its `_shared.js`/`style.css` paths are baked into the consumer
        // index.html files via `https://cfx-nui-_shared/...`. Building
        // first also fails fast if the vendor bundle itself is broken.
        await this.buildPlugin(shared.fullPath);
      }

      // Per-plugin Vite entries (PR-09) make cross-plugin webview builds
      // independent — App.tsx is no longer mutated, so parallel `vite build`
      // invocations cannot clobber each other.
      await Promise.all(
        consumers.map((plugin) => this.buildPlugin(plugin.fullPath))
      );

      this.logger.info(`✓ All ${plugins.length} plugins built successfully`);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      this.logger.error('Error building all plugins:', error);
      throw new Error(`Failed to build all plugins: ${errorMessage}`);
    }

    // After all plugins are built, reload them if requested
    if (reload && this.reloadManager) {
      try {
        this.logger.info('\n🔄 Reloading all resources...');
        const result = await this.reloadManager.reloadAllResources();

        if (result.success) {
          this.logger.info('✓ All resources reloaded successfully');
        } else {
          this.logger.warn('⚠ Some resources failed to reload');

          // Log failed resources
          if (result.results) {
            const failedResources = Object.entries(result.results)
              .filter(([_, success]) => !success)
              .map(([name]) => name);

            if (failedResources.length > 0) {
              this.logger.warn('Failed resources:', failedResources.join(', '));
            }
          }
        }
      } catch (error) {
        const errorMessage =
          error instanceof Error ? error.message : String(error);
        this.logger.warn(`⚠ Error reloading resources: ${errorMessage}`);
      }
    }
  }

  /**
   * Sweeps orphaned outputs from the dist tree.
   *
   * Removes:
   * - Any directory that contains an `fxmanifest.lua` but is no longer the
   *   destination of an active plugin (renamed/deleted/moved source plugin).
   * - Any directory whose name matches `<basename>.tmp.<digits>` — these are
   *   leftover staging dirs from a build process that crashed or is still
   *   running. We delete them indiscriminately because they only exist as
   *   transient build state; an in-flight build that races with the sweep
   *   will simply rebuild its own tmp dir.
   * - Empty wrapper directories left behind after either of the above.
   *
   * Intended to run when `--no-clean` is set, since that path otherwise lets
   * stale outputs accumulate forever (R-34). With `--clean` the entire dist
   * is wiped first, so this sweep is unnecessary.
   */
  async sweepOrphans(): Promise<void> {
    this.ensureInitialized();

    if (!fsSync.existsSync(this.distPath)) {
      return;
    }

    const activePlugins = this.fileManager.getAllPlugins();
    const expectedDirs = new Set<string>(
      activePlugins.map((plugin) =>
        path.normalize(this.getPluginDestDir(plugin))
      )
    );

    let orphansRemoved = 0;
    let tmpDirsRemoved = 0;

    const sweep = async (dir: string): Promise<void> => {
      let entries: fsSync.Dirent[];
      try {
        entries = await fs.readdir(dir, { withFileTypes: true });
      } catch (error) {
        // Dir disappeared mid-sweep — nothing to do.
        return;
      }

      const baseName = path.basename(dir);
      const isTmpDir = /\.tmp\.\d+$/.test(baseName);
      if (isTmpDir) {
        await fs.rm(dir, { recursive: true, force: true });
        tmpDirsRemoved++;
        return;
      }

      const containsManifest = entries.some(
        (e) => e.isFile() && e.name === 'fxmanifest.lua'
      );
      if (containsManifest && !expectedDirs.has(path.normalize(dir))) {
        await fs.rm(dir, { recursive: true, force: true });
        orphansRemoved++;
        return;
      }

      for (const entry of entries) {
        if (entry.isDirectory()) {
          await sweep(path.join(dir, entry.name));
        }
      }

      // Prune empty wrapper directories (e.g. `[character]/[auth]/` after the
      // last plugin under it was removed). Never prune the dist root itself.
      if (dir !== this.distPath) {
        try {
          const remaining = await fs.readdir(dir);
          if (remaining.length === 0) {
            await fs.rmdir(dir);
          }
        } catch {
          // Race with another process; ignore.
        }
      }
    };

    await sweep(this.distPath);

    if (orphansRemoved > 0 || tmpDirsRemoved > 0) {
      console.log(
        `✓ Orphan sweep: removed ${orphansRemoved} stale plugin output(s)` +
          (tmpDirsRemoved > 0
            ? ` and ${tmpDirsRemoved} leftover temp dir(s)`
            : '')
      );
    }
  }

  /**
   * Cleans the dist directory
   */
  async clean(): Promise<void> {
    this.ensureInitialized();

    try {
      this.logger.info(
        `Cleaning dist directory: ${this.pathToDisplay(this.distPath)}`
      );

      // Check if the directory exists
      if (fsSync.existsSync(this.distPath)) {
        // Remove all files and subdirectories
        await fs.rm(this.distPath, { recursive: true, force: true });

        // Recreate the empty directory
        await fs.mkdir(this.distPath, { recursive: true });
      }

      this.logger.info('✓ Dist directory cleaned successfully');
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      this.logger.error('Error cleaning dist directory:', error);
      throw new Error(`Failed to clean dist directory: ${errorMessage}`);
    }
  }

  /**
   * Helper method to ensure the manager is initialized
   * @private
   */
  private ensureInitialized(): void {
    if (!this.initialized) {
      throw new Error(
        'BuildManager must be initialized before use. Call initialize() first.'
      );
    }
  }

  /**
   * sha256 of every regular file under `dir`, mixed with each file's
   * dist-relative path (sorted, slash-normalized). Empty directories don't
   * contribute, but no plugin's reload semantics depend on them. Symlinks
   * and special files are skipped — the build only emits regular files
   * anyway, so encountering one would already indicate something else is
   * wrong.
   * @private
   */
  private async hashDir(dir: string): Promise<string> {
    const entries: string[] = [];
    const walk = async (current: string): Promise<void> => {
      const items = await fs.readdir(current, { withFileTypes: true });
      items.sort((a, b) => a.name.localeCompare(b.name));
      for (const item of items) {
        const full = path.join(current, item.name);
        if (item.isDirectory()) {
          await walk(full);
        } else if (item.isFile()) {
          entries.push(path.relative(dir, full).replace(/\\/g, '/'));
        }
      }
    };
    await walk(dir);
    entries.sort();
    const hash = crypto.createHash('sha256');
    for (const rel of entries) {
      hash.update(rel);
      hash.update('\0');
      hash.update(await fs.readFile(path.join(dir, rel)));
      hash.update('\0');
    }
    return hash.digest('hex');
  }

  /**
   * Determines if a file is a server-side script based on its path
   * @param filePath Path to check
   * @returns Whether the file is a server-side script
   * @private
   */
  /**
   * Path-segment platform classifier. Returns the platform name when the
   * file's immediate parent under the plugin root is one of `server`,
   * `client`, or `shared`. Used as a fallback when a script entry sits
   * outside the manifest globs (currently unused — manifest-driven
   * bundling is the source of truth — but kept available for future
   * tooling that needs to ask "is this a server file?").
   *
   * Replaces the previous substring sniff that matched any `/server/`
   * anywhere in the path, which misclassified files like
   * `client/server-utils/foo.ts` as server-platform bundles.
   */
  private getPathSegmentPlatform(
    pluginRoot: string,
    filePath: string
  ): EntryPlatform | null {
    const rel = path.relative(pluginRoot, filePath).replace(/\\/g, '/');
    const segments = rel.split('/').filter(Boolean);
    const head = segments[0];
    if (head === 'server' || head === 'client' || head === 'shared') {
      return head;
    }
    return null;
  }

  /**
   * Derive script entries from the plugin's manifest globs. A source file
   * (.ts or .js) becomes an entry only if its post-build `.js` path matches
   * one of `client_scripts`/`server_scripts`/`shared_scripts`. Files that
   * match no glob (e.g. `shared/types.ts`) are imported via the entry
   * graph but never emitted as standalone IIFEs.
   * @private
   */
  private getScriptEntries(plugin: Plugin): ScriptEntry[] {
    const manifest = plugin.manifest;
    if (!manifest) return [];

    const toGlobs = (s: ScriptList | undefined): string[] =>
      s === undefined ? [] : Array.isArray(s) ? s : [s];

    const serverGlobs = toGlobs(manifest.server_scripts);
    const clientGlobs = toGlobs(manifest.client_scripts);
    const sharedGlobs = toGlobs(manifest.shared_scripts);

    const entries: ScriptEntry[] = [];
    const seen = new Set<string>();

    for (const file of plugin.files) {
      const fn = file.fileName;
      const isCandidate =
        (fn.endsWith('.ts') && !fn.endsWith('.tsx')) ||
        (fn.endsWith('.js') && !fn.endsWith('.jsx'));
      if (!isCandidate) continue;
      if (seen.has(file.fullPath)) continue;

      const rel = path.relative(plugin.fullPath, file.fullPath).replace(/\\/g, '/');
      // Manifest globs target the post-build `.js` path, so map .ts → .js
      // for matching. The source file's actual extension is preserved when
      // bundling; this is just to compare against the manifest pattern.
      const outputJs = rel.replace(/\.ts$/, '.js');
      const matches = (globs: string[]) =>
        globs.some((g) => minimatch(outputJs, g));

      let platform: EntryPlatform | null = null;
      if (matches(serverGlobs)) platform = 'server';
      else if (matches(clientGlobs)) platform = 'client';
      else if (matches(sharedGlobs)) platform = 'shared';

      if (platform) {
        entries.push({ file, platform });
        seen.add(file.fullPath);
      }
    }

    return entries;
  }

  /**
   * Gets the list of packages to not inline
   * @param isServerScript Whether the file is a server-side script
   * @returns List of external packages
   * @private
   */
  private getExternalPackages(isServerScript: boolean): string[] {
    // For server scripts, externalize every Node built-in (both bare and
    // `node:`-prefixed). The previous hand-rolled list missed `node:`
    // imports, so `import 'node:fs'` was bundled into client/server JS
    // and either crashed or silently stubbed at runtime.
    return isServerScript ? [...NODE_BUILTIN_EXTERNALS] : [];
  }

  /**
   * Builds an fxmanifest.lua file from a plugin.json file
   * @param pluginNameOrPath The name or path of the plugin, or the Plugin object
   * @param outputDir Override the destination directory (used by transactional buildPlugin to stage into a temp dir)
   */
  async buildPluginManifest(
    pluginNameOrPath: string | Plugin,
    outputDir?: string
  ): Promise<void> {
    this.ensureInitialized();

    try {
      const plugin =
        typeof pluginNameOrPath === 'string'
          ? this.getPluginFromNameOrPath(pluginNameOrPath)
          : pluginNameOrPath;

      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      // Check if the plugin has a manifest
      if (!plugin.manifest) {
        this.logger.warn(
          `No manifest found for plugin ${plugin.pluginName}, skipping fxmanifest.lua generation`
        );
        return;
      }

      // Generate the fxmanifest.lua content
      const manifestContent = this.generateFxManifest(plugin);

      // Get the destination directory for the plugin
      const destDir = outputDir ?? this.getPluginDestDir(plugin);

      // Ensure the destination directory exists
      await fs.mkdir(destDir, { recursive: true });

      // Write the fxmanifest.lua file
      const manifestPath = path.join(destDir, 'fxmanifest.lua');
      await fs.writeFile(manifestPath, manifestContent, 'utf-8');

      this.logger.info(`✓ Generated fxmanifest.lua for plugin ${plugin.pluginName}`);
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      if (typeof pluginNameOrPath === 'string') {
        this.logger.error(
          `Error building manifest for plugin ${pluginNameOrPath}:`,
          error
        );
        throw new Error(
          `Failed to build manifest for plugin ${pluginNameOrPath}: ${errorMessage}`
        );
      } else {
        this.logger.error(
          `Error building manifest for plugin ${pluginNameOrPath.pluginName}:`,
          error
        );
        throw new Error(
          `Failed to build manifest for plugin ${pluginNameOrPath.pluginName}: ${errorMessage}`
        );
      }
    }
  }

  /**
   * Generates fxmanifest.lua content from a plugin manifest
   * @param plugin The plugin object containing the manifest
   * @returns The fxmanifest.lua content as a string
   * @private
   */
  private generateFxManifest(plugin: Plugin): string {
    const manifest = plugin.manifest!;
    let content = '';

    // Header comment. Intentionally NO `Generated on: <timestamp>` —
    // a wall-clock value would invalidate the dist hash on every
    // build and turn `distChanged` into a permanent `true`, defeating
    // the watcher's "skip reload when bytes unchanged" short-circuit.
    // Build time is recoverable from the file mtime if anyone needs it.
    content += `-- Generated from plugin.json by BuildManager\n`;
    content += `-- Plugin: ${plugin.pluginName}\n\n`;

    // Add resource metadata
    content += `-- Resource Metadata\n`;

    // Resource name (`name` is part of the schema; FXServer accepts it).
    if (manifest.name) {
      content += `name '${this.escapeLuaString(manifest.name)}'\n`;
    }

    // FX Version (default to "cerulean" if not specified)
    content += `fx_version '${manifest.fx_version || 'cerulean'}'\n`;

    // Games
    if (manifest.games && manifest.games.length > 0) {
      content += `games { '${manifest.games.join("', '")}' }\n`;
    } else {
      // Default to GTA5 if not specified
      content += `games { 'gta5' }\n`;
    }

    content += `\n`;

    // Basic metadata
    if (manifest.author) {
      content += `author '${this.escapeLuaString(manifest.author)}'\n`;
    }

    if (manifest.description) {
      content += `description '${this.escapeLuaString(
        manifest.description
      )}'\n`;
    }

    if (manifest.version) {
      content += `version '${this.escapeLuaString(manifest.version)}'\n`;
    }

    content += `\n`;

    // Scripts
    content += `-- What to run\n`;

    // Client scripts
    if (manifest.client_scripts) {
      if (Array.isArray(manifest.client_scripts)) {
        if (manifest.client_scripts.length === 1) {
          content += `client_script '${this.escapeLuaString(
            manifest.client_scripts[0]
          )}'\n`;
        } else if (manifest.client_scripts.length > 1) {
          content += `client_scripts {\n`;
          for (const script of manifest.client_scripts) {
            content += `    '${this.escapeLuaString(script)}',\n`;
          }
          content += `}\n`;
        }
      } else {
        content += `client_script '${this.escapeLuaString(
          manifest.client_scripts
        )}'\n`;
      }
    }

    // Server scripts
    if (manifest.server_scripts) {
      if (Array.isArray(manifest.server_scripts)) {
        if (manifest.server_scripts.length === 1) {
          content += `server_script '${this.escapeLuaString(
            manifest.server_scripts[0]
          )}'\n`;
        } else if (manifest.server_scripts.length > 1) {
          content += `server_scripts {\n`;
          for (const script of manifest.server_scripts) {
            content += `    '${this.escapeLuaString(script)}',\n`;
          }
          content += `}\n`;
        }
      } else {
        content += `server_script '${this.escapeLuaString(
          manifest.server_scripts
        )}'\n`;
      }
    }

    // Shared scripts
    if (manifest.shared_scripts) {
      if (Array.isArray(manifest.shared_scripts)) {
        if (manifest.shared_scripts.length === 1) {
          content += `shared_script '${this.escapeLuaString(
            manifest.shared_scripts[0]
          )}'\n`;
        } else if (manifest.shared_scripts.length > 1) {
          content += `shared_scripts {\n`;
          for (const script of manifest.shared_scripts) {
            content += `    '${this.escapeLuaString(script)}',\n`;
          }
          content += `}\n`;
        }
      } else {
        content += `shared_script '${this.escapeLuaString(
          manifest.shared_scripts
        )}'\n`;
      }
    }

    // UI page
    if (manifest.ui_page) {
      content += `\n-- UI\n`;
      content += `ui_page '${this.escapeLuaString(manifest.ui_page)}'\n`;
    }

    // Files
    if (manifest.files && manifest.files.length > 0) {
      content += `\n-- Files\n`;
      content += `files {\n`;
      for (const file of manifest.files) {
        content += `    '${this.escapeLuaString(file)}',\n`;
      }
      content += `}\n`;
    }

    // Data files
    if (manifest.data_files && manifest.data_files.length > 0) {
      content += `\n-- Data Files\n`;
      for (const dataFile of manifest.data_files) {
        if (Array.isArray(dataFile.files)) {
          for (const file of dataFile.files) {
            content += `data_file '${this.escapeLuaString(
              dataFile.type
            )}' '${this.escapeLuaString(file)}'\n`;
          }
        } else {
          content += `data_file '${this.escapeLuaString(
            dataFile.type
          )}' '${this.escapeLuaString(dataFile.files)}'\n`;
        }
      }
    }

    // Dependencies. A consumer plugin (one with a non-stub html/Page.tsx)
    // gains an implicit `dependency '_shared'` when the shared vendor
    // resource is registered — its generated index.html references
    // `https://cfx-nui-_shared/_shared.js` and `style.css`, which only
    // resolve once FXServer has started `_shared`. Skip the implicit
    // dependency for `_shared` itself and for any plugin whose author
    // already listed it explicitly.
    const explicitDeps = manifest.dependencies ?? [];
    const needsSharedDep =
      this.isSharedVendorAvailable() &&
      !this.isSharedVendorPlugin(plugin) &&
      this.pluginHasConsumerWebview(plugin) &&
      !explicitDeps.includes(SHARED_RESOURCE_NAME);
    const dependencies = needsSharedDep
      ? [SHARED_RESOURCE_NAME, ...explicitDeps]
      : explicitDeps;

    if (dependencies.length > 0) {
      content += `\n-- Dependencies\n`;
      if (dependencies.length === 1) {
        content += `dependency '${this.escapeLuaString(dependencies[0])}'\n`;
      } else {
        content += `dependencies {\n`;
        for (const dep of dependencies) {
          content += `    '${this.escapeLuaString(dep)}',\n`;
        }
        content += `}\n`;
      }
    }

    // Provides
    if (manifest.provide) {
      content += `\n-- Provides\n`;
      if (Array.isArray(manifest.provide)) {
        for (const provide of manifest.provide) {
          content += `provide '${this.escapeLuaString(provide)}'\n`;
        }
      } else {
        content += `provide '${this.escapeLuaString(manifest.provide)}'\n`;
      }
    }

    // Constraints (special handling)
    if (manifest.constraints) {
      content += `\n-- Runtime Constraints\n`;
      content += `dependencies {\n`;

      if (manifest.constraints.server) {
        content += `    '/server:${manifest.constraints.server}',\n`;
      }

      if (
        manifest.constraints.policy &&
        manifest.constraints.policy.length > 0
      ) {
        for (const policy of manifest.constraints.policy) {
          content += `    '/policy:${policy}',\n`;
        }
      }

      if (manifest.constraints.onesync) {
        content += `    '/onesync',\n`;
      }

      if (manifest.constraints.gameBuild) {
        content += `    '/gameBuild:${manifest.constraints.gameBuild}',\n`;
      }

      if (
        manifest.constraints.natives &&
        manifest.constraints.natives.length > 0
      ) {
        for (const native of manifest.constraints.natives) {
          content += `    '/native:${native}',\n`;
        }
      }

      content += `}\n`;
    }

    // Exports
    if (manifest.exports && manifest.exports.length > 0) {
      content += `\n-- Exports\n`;
      content += `exports {\n`;
      for (const exp of manifest.exports) {
        content += `    '${this.escapeLuaString(exp)}',\n`;
      }
      content += `}\n`;
    }

    // Server exports
    if (manifest.server_exports && manifest.server_exports.length > 0) {
      content += `\n-- Server Exports\n`;
      content += `server_exports {\n`;
      for (const exp of manifest.server_exports) {
        content += `    '${this.escapeLuaString(exp)}',\n`;
      }
      content += `}\n`;
    }

    // Map flag
    if (manifest.is_map) {
      content += `\n-- Map flag\n`;
      content += `this_is_a_map 'yes'\n`;
    }

    // Server only
    if (manifest.server_only) {
      content += `\n-- Server only\n`;
      content += `server_only 'yes'\n`;
    }

    // Loadscreen
    if (manifest.loadscreen) {
      content += `\n-- Loadscreen\n`;
      content += `loadscreen '${this.escapeLuaString(manifest.loadscreen)}'\n`;

      if (manifest.loadscreen_manual_shutdown) {
        content += `loadscreen_manual_shutdown 'yes'\n`;
      }
    }

    // Honor `config` from plugin.json: emit each entry as a `set` directive
    // so FXServer-side convars are available without a separate convars block.
    if (manifest.config && Object.keys(manifest.config).length > 0) {
      content += `\n-- Config\n`;
      for (const [rawKey, value] of Object.entries(manifest.config)) {
        const key = this.assertSafeManifestKey(rawKey, plugin.pluginName);
        content += `set '${key}' ${this.formatLuaScalar(value, key, plugin.pluginName)}\n`;
      }
    }

    // Add any custom properties (anything not in the standardProps allowlist)
    const customProps = this.getCustomProperties(manifest);
    if (Object.keys(customProps).length > 0) {
      content += `\n-- Additional Metadata\n`;
      for (const [rawKey, value] of Object.entries(customProps)) {
        const key = this.assertSafeManifestKey(rawKey, plugin.pluginName);
        if (Array.isArray(value)) {
          for (const val of value) {
            content += `${key} ${this.formatLuaScalar(val, key, plugin.pluginName)}\n`;
          }
        } else {
          content += `${key} ${this.formatLuaScalar(value, key, plugin.pluginName)}\n`;
        }
      }
    }

    return content;
  }

  /**
   * Custom-property keys must be valid Lua identifiers (FXServer parses these
   * as bareword directives). Reject anything that would produce a syntax error
   * in the generated fxmanifest.lua.
   */
  private assertSafeManifestKey(key: string, pluginName: string): string {
    if (!/^[a-z_][a-z0-9_]*$/i.test(key)) {
      throw new Error(
        `Invalid plugin.json key for plugin ${pluginName}: '${key}' must match /^[a-z_][a-z0-9_]*$/i`
      );
    }
    return key;
  }

  /**
   * Type-aware emission for fxmanifest scalars:
   *  - boolean -> 'yes' | 'no' (FXServer convention)
   *  - number  -> unquoted Lua number
   *  - string  -> single-quoted, escaped
   *  - object  -> hard error (silently stringifying produces a useless directive)
   */
  private formatLuaScalar(
    value: unknown,
    keyForError: string,
    pluginName: string
  ): string {
    if (typeof value === 'boolean') {
      return `'${value ? 'yes' : 'no'}'`;
    }
    if (typeof value === 'number') {
      if (!Number.isFinite(value)) {
        throw new Error(
          `Invalid numeric value for ${keyForError} in plugin ${pluginName}: ${value}`
        );
      }
      return String(value);
    }
    if (typeof value === 'string') {
      return `'${this.escapeLuaString(value)}'`;
    }
    if (value === null || typeof value === 'undefined') {
      throw new Error(
        `Null/undefined value for ${keyForError} in plugin ${pluginName} cannot be emitted to fxmanifest.lua`
      );
    }
    // Objects (and any other non-scalar) are not representable as a single
    // Lua directive; refuse rather than emit a useless stringified value.
    throw new Error(
      `Object value for ${keyForError} in plugin ${pluginName} is not supported in fxmanifest.lua emission`
    );
  }

  /**
   * Escapes special characters in Lua strings
   * @param str The string to escape
   * @returns Escaped string safe for Lua
   * @private
   */
  private escapeLuaString(str: string): string {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'")
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  }

  /**
   * Gets custom properties from the manifest (properties not explicitly handled)
   * @param manifest The plugin manifest
   * @returns Object with custom properties
   * @private
   */
  private getCustomProperties(manifest: PluginManifest): Record<string, any> {
    const standardProps = [
      'name',
      'description',
      'author',
      'version',
      'fx_version',
      'games',
      'client_scripts',
      'server_scripts',
      'shared_scripts',
      'ui_page',
      'dependencies',
      'provide',
      'constraints',
      'files',
      'data_files',
      'is_map',
      'server_only',
      'loadscreen',
      'loadscreen_manual_shutdown',
      'exports',
      'server_exports',
      'config',
    ];

    const custom: Record<string, any> = {};

    for (const [key, value] of Object.entries(manifest)) {
      if (!standardProps.includes(key)) {
        custom[key] = value;
      }
    }

    return custom;
  }

  /**
   * Builds other files for a plugin by copying untreated extensions to the output folder
   * @param pluginNameOrPath The name or path of the plugin, or the Plugin object
   * @param outputDir Override the destination directory (used by transactional buildPlugin to stage into a temp dir)
   */
  async buildPluginOtherFiles(
    pluginNameOrPath: string | Plugin,
    outputDir?: string,
    excludePaths?: ReadonlySet<string>
  ): Promise<void> {
    this.ensureInitialized();

    try {
      const plugin =
        typeof pluginNameOrPath === 'string'
          ? this.getPluginFromNameOrPath(pluginNameOrPath)
          : pluginNameOrPath;

      if (!plugin) {
        throw new Error(`Plugin not found: ${pluginNameOrPath}`);
      }

      // What gets copied as "other":
      //   - .lua / .json have dedicated build steps (buildPluginLua /
      //     buildPluginJson) — skip here, they're already handled.
      //   - .ts / .tsx are bundling sources — never copy raw.
      //   - .js / .jsx are bundled IF the manifest declares them in
      //     *_scripts (then buildPluginJs writes the bundle); otherwise
      //     they're plain assets (e.g. NUI `html/js/*.js` referenced from
      //     `<script src>` tags) and MUST be copied here. Excluding them
      //     unconditionally — as a previous version did — silently dropped
      //     qb-core's NUI scripts, leaving every SendNUIMessage with no
      //     listener: no toasts, no DrawText popup.
      const scriptedJsPaths = new Set(
        this.getScriptEntries(plugin).map((e) => e.file.fullPath)
      );
      const isHandledElsewhere = (file: File): boolean => {
        const fn = file.fileName;
        if (fn.endsWith('.lua') || fn.endsWith('.json')) return true;
        if (fn.endsWith('.ts') || fn.endsWith('.tsx')) return true;
        if (fn.endsWith('.js') || fn.endsWith('.jsx')) {
          return scriptedJsPaths.has(file.fullPath);
        }
        return false;
      };
      // Same exclusion shape as buildPluginJson — drop assets that the
      // script bundlers already inlined.
      const isExcluded = excludePaths && excludePaths.size > 0
        ? (file: File) => excludePaths.has(path.normalize(file.fullPath))
        : () => false;
      const otherFiles = plugin.files.filter(
        (file) => !isHandledElsewhere(file) && !isExcluded(file)
      );

      for (const file of otherFiles) {
        this.logger.info(`Copying other file: ${file.fileName}`);
      }

      if (otherFiles.length === 0) {
        this.logger.info(`No other files found in plugin ${plugin.pluginName}`);
        return;
      }

      // Log the types of files being copied
      const extensionCounts = new Map<string, number>();
      for (const file of otherFiles) {
        const ext = path.extname(file.fileName).toLowerCase();
        extensionCounts.set(ext, (extensionCounts.get(ext) || 0) + 1);
      }

      const extensionSummary = Array.from(extensionCounts.entries())
        .map(([ext, count]) => `${count} ${ext || '(no extension)'} file(s)`)
        .join(', ');

      this.logger.info(
        `Copying other files for plugin ${plugin.pluginName}: ${extensionSummary}`
      );

      await this.copyFilesToDist(plugin, otherFiles, outputDir);
      this.logger.info(
        `✓ Built ${otherFiles.length} other file(s) for plugin ${plugin.pluginName}`
      );
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      if (typeof pluginNameOrPath === 'string') {
        this.logger.error(
          `Error building other files for plugin ${pluginNameOrPath}:`,
          error
        );
        throw new Error(
          `Failed to build other files for plugin ${pluginNameOrPath}: ${errorMessage}`
        );
      } else {
        this.logger.error(
          `Error building other files for plugin ${pluginNameOrPath.pluginName}:`,
          error
        );
        throw new Error(
          `Failed to build other files for plugin ${pluginNameOrPath.pluginName}: ${errorMessage}`
        );
      }
    }
  }
}

export { BuildManager };
