services:
  fivem:
    build: ./
    env_file: .env
    ports:
      - '30120:30120/tcp'
      - '30120:30120/udp'
      - '40120:40120/tcp'
      - '3414:3414'
    volumes:
      - ./txData:/root/binaries/txData
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 6G
        reservations:
          cpus: '3'
          memory: 4G

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  db_data:
