// Auto-generated by WebviewBuilder
// Generated on: 2025-04-24T16:20:27.724Z

import Page from '../../plugins/[misc]/example/html/Page.tsx';

function App() {
  return <Page />;
}

export default App;
