// Auto-generated by WebviewBuilder
// Generated on: 2025-04-24T13:26:53.047Z

import Page from '../../plugins/[misc]/example/html/Page.tsx';

function App() {
  return <Page />;
}

export default App;
