// Auto-generated by WebviewBuilder
// Generated on: 2025-04-24T01:29:27.533Z

import React from 'react';
import Page from '../../plugins/[misc]/example/html/Page.tsx';

function App() {
  return <Page />;
}

export default App;
